### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by venky9885** [ehoraizon/auto_update#1]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot create file, path = 'C:\Users\venky\Downloads\soft_desk.msix?alt=media&token=2c03f884-152d-4d64-9375-8275e901daa6' (OS Error: The filename, directory name, or volume label syntax is incorrect.

, errno = 123)
#0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
<asynchronous suspension>
#1      downloadFile (package:auto_update/desktop.dart:20:3)
<asynchronous suspension>
#2      AutoUpdate.downloadAndUpdate (package:auto_update/auto_update.dart:46:26)
<asynchronous suspension>
#3      _MyHomePageState.build.<anonymous closure> (package:soft_desk/main.dart:474:21)
<asynchronous suspension>


```
Check it

**Comment by ehoraizon** [comment]
Hello, I'm busy at the moment, but when I'm free I'll check the issue. If it helps, the problem is this part of the path "?alt=media&token=2c03f884-152d-4d64-9375-8275e901daa6".

**Comment by ehoraizon** [comment]
@venky9885 Is this a private repository? Could you provide more information about the context in which you are using the plugin?
